### ISSUE TITLE
Port to Plasma 6

### ISSUE THREAD

**Issue by baduhai** [peterfajdiga/karousel#36] opened 2024-03-04 20:33 UTC
My computer has become nearly unusable without this plugin, it's almost a necessity on ultrawide. I hope you plan on porting this to Plasma 6.

There have been breaking changes to Plasma's API, but I couldn't really find a porting guide.

**Comment by peterfajdiga** [comment] 2024-03-09 18:01
Duplicate of #29

**Closed by peterfajdiga** 2024-03-09 18:01 UTC
