### ISSUE TITLE
APPEAL REQUEST: Carousel vs Floating

### ISSUE THREAD

**Issue by gleyconJ** [peterfajdiga/karousel#70] opened 2024-11-08 02:22 UTC
Hello, sorry for the discomfort once again.
But how about if we could have an additional tab in the Karoussel settings entitled Workspace, and this tab could recognize how many work areas I have for activity (which are always the same quantities in the current stage). But we could choose if the windows "initially open" like a carousel or floating.

Like this:

 Area 1
 Carousel =={} Floating

 Area 2
 Carousel {}== Floating

 Area 3
 Carousel {}== Floating

 Area 4
 Carousel {}== Floating

 Area 5
 Carousel =={} Floating

 §§§§§ §§§§§§ §§§§§§§§§§§§§§§§

 Hence the person can appoint the areas manually with a symbol that he finds appropriate to remind him of his choices. For example:

 Area 1 = Main 🪟
 Area 2 = Alternative 🎠
 Area 3 = Internet 🎠
 Area 4 = torrents 🎠
 Area 5 = Extra 🪟
 
As Karoussel already has 12 planned area, it can even be 12 ares by default on this configuration tab. No matter if the user has 1, 2 or 20.

**Comment by peterfajdiga** [comment] 2024-11-08 08:36
Duplicate of https://github.com/peterfajdiga/karousel/issues/64

**Closed by peterfajdiga** 2024-11-08 08:36 UTC
